# Configuration H2 Persistante (Sauvegarde dans le dossier /data)
spring.datasource.url=jdbc:h2:file:./data/atlasidb;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Désactiver open-in-view
spring.jpa.open-in-view=false

server.port=8080
